### ISSUE TITLE
Problem with package hosted on Gitlab 

### ISSUE THREAD

**Issue by bsmelo** [Lobaro/coap-go#2]
Hello,

Does this have any dependency on a [apparently private] gitlab repository?
I'm unable to `go get` it due to this:
```
 $ go get -u github.com/lobaro/coap-go
package github.com/lobaro/coap-go
        imports gitlab.com/lobaro/lobaro-coap-go/coap: unrecognized import path "gitlab.com/lobaro/lobaro-coap-go/coap"
```

Any help is appreciated.

Thanks & Regards,
Bruno Melo.

**Comment by niondir** [comment]
Thanks for reporting.

I will have a look. Until then try `go get -u github.com/lobaro/coap-go/coap` for the client package.

The code that leads to failures is related to the Go wrapper around our C lib. The wrapper is not finished anyway and I tend to implement the server in Go from scratch as soon as I have the need and time.

**Comment by niondir** [comment]
Go get should work now. Since there is some CGO involved you need the 32-bit compiler if you are planning to play around with the unfinished server wrapper. Else please stick with `go get -u github.com/lobaro/coap-go/coap` for now.

I welcome any feedback about the libs. Especially the coap client over RS232 with SLIP and SlipMux is well supported and used in several projects at our company.

**Comment by niondir** [comment]
I updated the readme to clear up things. Let me know what you are looking for. I'm happy to help.

**Comment by bsmelo** [comment]
Hi @Niondir, thanks for the prompt response. :+1: 
The new `readme` makes things a little bit clearer for me now.

What I want to play with is precisely the server, just being able to run it so it's there listening on an UDP port so I can see CoAP packets going back-and-forth should suffice my needs.
I'd actually like to do this with both `lobaro-coap` and `lobaro-go-coap`; but from the `readme` on the [C repo](https://github.com/lobaro/lobaro-coap) I got the sense I would need actual hardware, but I just want to run it on Linux for the time being... So, I went to check if I could run this simple server app using this repo.

I should be able to do that, right?

Although I can `go get` now, and apparently everything is fine with `go test`, I still can't `go run main.go`:
```
 $ export GOPATH=~/go      
 $ export GOBIN=$GOPATH/bin
 $ export PATH=$PATH:$GOBIN
 $ go get -u github.com/lobaro/coap-go
# github.com/Lobaro/coap-go/coap-old
In file included from /home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/go_api.go:7:0:
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/interface/mem/coap_mem.c: In function ‘coap_mem_stats’:
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/interface/mem/coap_mem.c:107:2: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int32_t’ [-Wformat=]
  INFO("- CoAP mem usage: dynamic: [%ld] dynamic+static: [%ld] free: [%ld] biggest shunk: [%ld] get/releases: [%ld|%ld]\r\n",(int32_t)curalloc-StaticAllocation, (int32_t)curalloc, (int32_t)totfree, (int32_t)maxfree,nget,nrel );
  ^
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/interface/mem/coap_mem.c:107:2: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/interface/mem/coap_mem.c:107:2: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘int’ [-Wformat=]
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/interface/mem/coap_mem.c:107:2: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 6 has type ‘int’ [-Wformat=]
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/interface/mem/coap_mem.c:107:2: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘int32_t’ [-Wformat=]
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/interface/mem/coap_mem.c:107:2: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 8 has type ‘int32_t’ [-Wformat=]
# github.com/Lobaro/coap-go/coap-old
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_main.c: In function ‘CoAP_Init’:
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_main.c:29:2: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 4 has type ‘uint8_t *’ [-Wformat=]
  INFO("CoAP Available memory: %d bytes at 0x%x\r\n",MemorySize, pMemory);
  ^
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_main.c:30:2: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  INFO("CoAP Interaction size: %d byte\r\n",sizeof(CoAP_Interaction_t));
  ^
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_main.c:31:2: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  INFO("CoAP_Res_t size: %d byte\r\n",sizeof(CoAP_Res_t));
  ^
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_main.c:32:2: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  INFO("CoAP_Message_t size: %d byte\r\n",sizeof(CoAP_Message_t));
  ^
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_main.c:33:2: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  INFO("CoAP_option_t size: %d byte\r\n",sizeof(CoAP_option_t));
  ^
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_main.c:34:2: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  INFO("CoAP_Observer_t size: %d byte\r\n",sizeof(CoAP_Observer_t));
  ^
# github.com/Lobaro/coap-go/coap-old
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_message.c: In function ‘CoAP_PrintMsg’:
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_message.c:531:5: warning: too many arguments for format [-Wformat-extra-args]
     INFO("  [00]", pOption->Value[j]);
     ^
# github.com/Lobaro/coap-go/coap-old
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_options.c: In function ‘CoAP_printOptionsList’:
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_options.c:476:5: warning: too many arguments for format [-Wformat-extra-args]
     INFO("  [0x00]", pOptListBegin->Value[j]);
     ^
# github.com/Lobaro/coap-go/coap-old
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_resource.c: In function ‘CoAP_PrintResource’:
/home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/coap_resource.c:347:3: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
   INFO("Token:%llu - ", pOpserver->Token);
   ^


 $ go test github.com/lobaro/coap-go
ok      github.com/lobaro/coap-go       0.006s


 $ go run main.go 
main.go:4:2: cannot find package "gitlab.com/lobaro/lobaro-coap-go/coap" in any of:
        /usr/lib/go/src/pkg/gitlab.com/lobaro/lobaro-coap-go/coap (from $GOROOT)
        /home/bruno/go/src/gitlab.com/lobaro/lobaro-coap-go/coap (from $GOPATH)
```

There really isn't any `gitlab.com` folder under my `$GOPATH`, but it is at least weird that `go test` didn't raise such issues - I'm very new to go itself, but I guess this wouldn't be a problem just to run the application.

**Comment by bsmelo** [comment]
Whoops, nothing like a `git pull`; my bad.
I can run it and interact using Copper now.

Thanks again!

**Comment by niondir** [comment]
@bsmelo When you are looking for a Linux based server you might be better off with other projects yet. 

From a company perspective we have more need for embedded CoAP servers on our hardware (e.g. STM32 Cortex-M3), where the Linux PC (often something like a Raspberry Pi) ist just acting as CoAP client to the hardware, communicating via RS232. Over TCP/IP and between Linux machines we mostly stick with HTTP or MQTT, I do not see so much reason to change this.

But as I mentioned I'm definitely interested in providing an pure Go CoAP Server. So **if there is some need and willingness to help with the implementation** I would start with some basic structure and features on which we can build up.
Especially a feature like a CoAP to HTTP proxy would even fit some of our usecases and could save some manual mapping code.

There is already a lot of useful code in this repo due to the Client. Dealing with messages, options, etc. is all possible already.


**Edit:** About your posted warnings / errors: We refactored some bits of the C lib, maybe the Go Wrapper is not accurate anymore.
